import pandas as pd
import streamlit as st

def render_basic_overview(df: pd.DataFrame, overview: dict, info_str: str) -> None:
    """
    Render a basic overview of the dataset in the Streamlit UI.

    Displays technical information, dataset shape, unique value counts
    and descriptive statistics.

    Parameters
    ----------
    df : pd.DataFrame
        Input DataFrame (used only for display context).
    overview : dict
        Precomputed overview statistics generated by `compute_basic_overview`.
    info_str : str
        Text output of `df.info()` captured as a string.
    """
    st.markdown('<h4>Basic information:</h4>', unsafe_allow_html=True)
    st.text(info_str)

    rows, cols = overview["shape"]
    st.write(f"Columns: {cols}")
    st.write(f"Rows: {rows}")

    st.markdown('<h4>Nunique values</h4>', unsafe_allow_html=True)
    st.write(overview["nunique"])

    st.markdown('<h4>Unique values in total:</h4>', unsafe_allow_html=True)
    st.write(overview["unique_total"])

    st.markdown('<h4>Descriptive Statistics</h4>', unsafe_allow_html=True)
    st.write(overview["describe"])